name: Keep Warm

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual testing from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application to Wake DB
        # curl flags:
        # -I : Fetch headers only (faster)
        # -L : Follow redirects (if http -> https)
        # -f : Fail the job if the server returns an error code (4xx/5xx)
        # ?t=$(date +%s) : Adds a unique timestamp query to BYPASS THE VERCEL CACHE
        run: curl -I -L -f "https://tracku.me/ping?t=$(date +%s)"